CREATE TABLE "SECTORS"
(   "SECTOR_ID" NUMBER(8, 0),
    "SECTOR_NAME" VARCHAR2(25 BYTE)
);

CREATE TABLE "PACKAGES"
(   "PACK_ID" NUMBER(8, 0),
    "SPEED" VARCHAR2(10 BYTE),
    "MONTHLY_PAYMENT" NUMBER(8, 0),
    "SECTOR_ID" NUMBER(8, 0),
    "START_DATE" DATE);

CREATE TABLE "CUSTOMERS"
(   "CUSTOMER_ID" NUMBER(8,0),
    "FIRST_NAME" VARCHAR2(25 BYTE),
    "LAST_NAME" VARCHAR2(25 BYTE),
    "CITY" VARCHAR2(45 BYTE),
    "STATE" VARCHAR2(25 BYTE),
    "STREET" VARCHAR2(40 BYTE),
    "MAIN_PHONE_NUM" VARCHAR2(12 BYTE),
    "SECONDARY_PHONE_NUM" VARCHAR2(12 BYTE),
    "FAX" VARCHAR2(12 BYTE),
    "MONTHLY_DISCOUNT" NUMBER(4,2),
    "PACK_ID" NUMBER(8,0),
    "BIRTH_DATE" DATE,
    "JOIN_DATE" DATE
);
