SELECT R.A
FROM R, S
WHERE R.A = S.A
MINUS
SELECT R.A
FROM R, T
WHERE R.A = T.A;

SELECT COUNT(*)
FROM (SELECT * FROM tableA); /* 389 */

SELECT COUNT(*)
FROM (SELECT * FROM tableB); /* 217 */

SELECT COUNT(*)
FROM (SELECT * FROM tableA INTERSECT SELECT * FROM tableB); /* 0 */

SELECT COUNT(*)
FROM (SELECT * FROM tableA MINUS SELECT * FROM tableB); /* 389 */

SELECT COUNT(*)
FROM (SELECT * FROM tableB MINUS SELECT * FROM tableA); /* 89 */
