/* Foreign Key (constraints) :
   manage related data across tables by creating references between them */
CREATE TABLE Enrolled (
    student_id CHAR(20),
    cid CHAR(20),
    grade CHAR(10),
    PRIMARY KEY (student_id, cid),
    FOREIGN KEY (student_id) REFERENCES Students(sid)
);

ALTER TABLE "SECTORS" ADD CONSTRAINT "SECTOR_ID_PK" PRIMARY KEY ("SECTOR_ID");
ALTER TABLE "PACKAGES" ADD CONSTRAINT "PACK_ID_PK" PRIMARY KEY ("PACK_ID");
ALTER TABLE "PACKAGES" ADD CONSTRAINT "SECTOR_ID_FK" FOREIGN KEY ("SECTOR_ID")
    REFERENCES "SECTORS" ("SECTOR_ID") ENABLE;
ALTER TABLE "CUSTOMERS" ADD CONSTRAINT "CUSTOMER_ID_PK" PRIMARY KEY ("CUSTOMER_ID");
ALTER TABLE "CUSTOMERS" ADD CONSTRAINT "PACK_ID_FK" FOREIGN KEY ("PACK_ID");
    REFERENCES "PACKAGES" ("PACK_ID") ENABLE;
